amcl:
  ros__parameters:
    use_sim_time: False
    scan_topic: /scan
    base_frame_id: base_link
    odom_frame_id: odom
    map_frame_id: map
    min_particles: 500
    max_particles: 2000

bt_navigator:
  ros__parameters:
    default_nav_to_pose_bt_xml: "navigate_to_pose_bt.xml"

controller_server:
  ros__parameters:
    expected_frequency: 20.0
    min_speed_xy: 0.0
    max_speed_xy: 0.5
    min_speed_theta: 0.0
    max_speed_theta: 1.0
